stages:
  - test

test-all-labs:
  stage: test
  tags:
    - vm-linux-x86-32cpu-64gb
  timeout: 99h
  script:
    - sudo ./scripts/install-dependencies.sh
    - curl -fSL -o /tmp/sonic-vs.img.gz https://pub-b38eb23466d442f88f85da770f4feea7.r2.dev/sonic-vs.img.gz
    - sudo ./scripts/runlab.sh --image /tmp/sonic-vs.img.gz
